package com.commerceinsight.shared.base;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.io.Serializable;
import java.time.Instant;
import java.util.UUID;

/**
 * BaseEntity — foundation for all JPA entities in Commerce Insight AI.
 *
 * <p>Provides:
 * <ul>
 *   <li>UUID primary key (generated by the database)</li>
 *   <li>Auditing timestamps: createdAt, updatedAt</li>
 *   <li>Soft delete support via deletedAt</li>
 * </ul>
 *
 * <p>Architecture Rule: Every domain entity MUST extend this class.
 * Entities with soft delete must annotate the subclass with
 * {@code @SQLRestriction("deleted_at IS NULL")}.
 */
@Getter
@Setter
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity implements Serializable {

    /**
     * Primary key — UUID generated by PostgreSQL via gen_random_uuid().
     * Never set manually in application code.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /**
     * Timestamp when this record was created.
     * Set automatically by Spring Data Auditing on INSERT.
     */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Timestamp when this record was last modified.
     * Updated automatically by Spring Data Auditing on UPDATE.
     */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * Soft-delete timestamp. Null means the record is active.
     * Set to Instant.now() to soft-delete. Never use hard DELETE.
     *
     * <p>Entities that support soft delete must add
     * {@code @SQLRestriction("deleted_at IS NULL")} at the class level.
     */
    @Column(name = "deleted_at")
    private Instant deletedAt;

    /**
     * Convenience method to check whether this entity is soft-deleted.
     *
     * @return true if deleted_at is set
     */
    public boolean isDeleted() {
        return deletedAt != null;
    }

    /**
     * Soft-delete this entity by setting deletedAt to the current time.
     */
    public void softDelete() {
        this.deletedAt = Instant.now();
    }
}
