package com.commerceinsight.analytics.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
import java.util.UUID;

/**
 * TopProductEntry — one row in the top-products leaderboard.
 *
 * <p>Uses historical snapshot fields ({@code skuSnapshot}, {@code productNameSnapshot})
 * so the result is correct even when a product has been modified or deleted.
 * {@code productId} may be null if the product record was hard-deleted
 * (which the application does not do, but is handled defensively).
 */
@Schema(description = "One entry in the top products by revenue or quantity sold")
public record TopProductEntry(

        @Schema(description = "Product UUID. Null if the product was deleted.")
        UUID productId,

        @Schema(description = "SKU as captured at order time (historical snapshot)")
        String sku,

        @Schema(description = "Product name as captured at order time (historical snapshot)")
        String productName,

        @Schema(description = "Total quantity units sold across revenue-eligible orders in period")
        long quantitySold,

        @Schema(description = "Total revenue generated by this product in period")
        BigDecimal revenue
) {}
