/**
 * features/export/pages/ExportPage.tsx
 *
 * Route: /export  (any authenticated user — the backend allows STAFF+).
 *
 * Export Center: pick a report, choose XLSX or PDF, set the supported filters,
 * and download a file generated by the Sprint 11A backend. Exports are
 * synchronous binary downloads — there is no job history or progress polling.
 */
import { useCallback, useMemo, useState } from 'react'
import { FileDown } from 'lucide-react'
import { useCategoryOptions } from '@/features/products/hooks/useCategories'
import { useCustomerGroupOptions } from '@/features/customers/hooks/useCustomerGroups'
import { ExportTypeSelector } from '../components/ExportTypeSelector'
import { ExportFormatSelector } from '../components/ExportFormatSelector'
import { ExportFilters } from '../components/ExportFilters'
import { ExportSummary } from '../components/ExportSummary'
import { ExportButton } from '../components/ExportButton'
import { useExportReport } from '../hooks/useExport'
import { EXPORT_REPORT_MAP } from '../constants'
import {
  EMPTY_EXPORT_FORM,
  type ExportFormState,
  type ExportFormat,
  type ExportReportType,
} from '../types/export.types'
import { buildExportRequest, validateExportForm } from '../utils/buildRequest'

const cardStyle = {
  background: 'var(--bg-surface)',
  borderColor: 'var(--border-default)',
}

function SectionCard({
  title,
  children,
}: {
  title: string
  children: React.ReactNode
}) {
  return (
    <section className="rounded-xl border p-5 space-y-4" style={cardStyle}>
      <h2 className="text-body-sm font-semibold" style={{ color: 'var(--text-primary)' }}>
        {title}
      </h2>
      {children}
    </section>
  )
}

export function ExportPage() {
  const [reportType, setReportType] = useState<ExportReportType>('PRODUCTS')
  const [format, setFormat] = useState<ExportFormat>('XLSX')
  const [form, setForm] = useState<ExportFormState>(EMPTY_EXPORT_FORM)
  const [customerLabel, setCustomerLabel] = useState<string | null>(null)

  const exportMutation = useExportReport()
  const isPending = exportMutation.isPending

  // Cheap, cached lookups — used only to label ids in the summary.
  const { data: categoryOptions = [] } = useCategoryOptions()
  const { data: groupOptions = [] } = useCustomerGroupOptions()

  const categoryLabel = useMemo(
    () => categoryOptions.find((o) => o.value === form.categoryId)?.label,
    [categoryOptions, form.categoryId],
  )
  const groupLabel = useMemo(
    () => groupOptions.find((o) => o.value === form.groupId)?.label,
    [groupOptions, form.groupId],
  )

  // ── Handlers ──────────────────────────────────────────────────────────
  const handleReportChange = useCallback(
    (type: ExportReportType) => {
      if (type === reportType) return
      setReportType(type)
      setForm(EMPTY_EXPORT_FORM) // reset: no param may leak between reports
      setCustomerLabel(null)
    },
    [reportType],
  )

  const handleFormChange = useCallback((patch: Partial<ExportFormState>) => {
    setForm((prev) => ({ ...prev, ...patch }))
  }, [])

  const validationError = useMemo(
    () => validateExportForm(reportType, form),
    [reportType, form],
  )

  const handleExport = useCallback(() => {
    if (isPending || validationError) return
    exportMutation.mutate(buildExportRequest(reportType, format, form))
  }, [isPending, validationError, exportMutation, reportType, format, form])

  const activeMeta = EXPORT_REPORT_MAP[reportType]

  return (
    <div className="space-y-6 animate-fade-in">
      {/* ── Header ────────────────────────────────────────────────────── */}
      <div className="flex items-start gap-3">
        <div
          className="mt-0.5 flex h-10 w-10 shrink-0 items-center justify-center rounded-xl"
          style={{ background: 'rgba(99,102,241,0.12)' }}
        >
          <FileDown className="h-5 w-5" style={{ color: 'var(--accent-400)' }} />
        </div>
        <div>
          <h1 className="text-heading-2 font-bold" style={{ color: 'var(--text-primary)' }}>
            Export Reports
          </h1>
          <p className="text-body-sm mt-1" style={{ color: 'var(--text-secondary)' }}>
            Export products, customers, orders and analytics as XLSX or PDF.
          </p>
        </div>
      </div>

      {/* ── Step 1: report ───────────────────────────────────────────── */}
      <SectionCard title="1 · Select a report">
        <ExportTypeSelector
          value={reportType}
          onChange={handleReportChange}
          disabled={isPending}
        />
      </SectionCard>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
        {/* ── Left: format + filters ────────────────────────────────── */}
        <div className="space-y-6 lg:col-span-2">
          <SectionCard title="2 · Format">
            <ExportFormatSelector
              value={format}
              onChange={setFormat}
              disabled={isPending}
            />
          </SectionCard>

          <SectionCard title={`3 · Filters — ${activeMeta.label}`}>
            <p className="text-caption -mt-1" style={{ color: 'var(--text-muted)' }}>
              {activeMeta.description}
            </p>
            <ExportFilters
              reportType={reportType}
              value={form}
              onChange={handleFormChange}
              disabled={isPending}
              onCustomerLabelChange={setCustomerLabel}
            />
          </SectionCard>
        </div>

        {/* ── Right: summary + action ───────────────────────────────── */}
        <div className="lg:col-span-1">
          <section
            className="rounded-xl border p-5 space-y-4 lg:sticky lg:top-6"
            style={cardStyle}
          >
            <h2
              className="text-body-sm font-semibold"
              style={{ color: 'var(--text-primary)' }}
            >
              Summary
            </h2>
            <ExportSummary
              reportType={reportType}
              format={format}
              form={form}
              categoryLabel={categoryLabel}
              groupLabel={groupLabel}
              customerLabel={customerLabel ?? undefined}
            />
            <div className="h-px" style={{ background: 'var(--border-subtle)' }} />
            <ExportButton
              onExport={handleExport}
              isPending={isPending}
              disabledReason={validationError}
            />
          </section>
        </div>
      </div>
    </div>
  )
}